/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tp6grupo17ej2;

import java.util.TreeSet;

/**
 *
 * @author Julian
 */
public class VistaPrincipal extends javax.swing.JFrame {
  private static TreeSet<Producto> productos = new TreeSet<>((Producto p1, Producto p2) -> Long.compare(p1.getCodigo(), p2.getCodigo()));

public static TreeSet<Producto> getProductos() {
    return productos;
}
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VistaPrincipal.class.getName());

    /**
     * Creates new form VistaPrincipal
     */
    public VistaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        dskPrincipal = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuAdministracion = new javax.swing.JMenu();
        itemMenuGestion = new javax.swing.JMenuItem();
        menuConsultas = new javax.swing.JMenu();
        itemMenuCategoria = new javax.swing.JMenuItem();
        itemMenuPrecio = new javax.swing.JMenuItem();
        itemMenuNombre = new javax.swing.JMenuItem();

        jMenu1.setText("jMenu1");

        jMenu2.setText("jMenu2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout dskPrincipalLayout = new javax.swing.GroupLayout(dskPrincipal);
        dskPrincipal.setLayout(dskPrincipalLayout);
        dskPrincipalLayout.setHorizontalGroup(
            dskPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 772, Short.MAX_VALUE)
        );
        dskPrincipalLayout.setVerticalGroup(
            dskPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 574, Short.MAX_VALUE)
        );

        menuAdministracion.setText("Administracion");

        itemMenuGestion.setText("Gestion de Productos");
        itemMenuGestion.addActionListener(this::itemMenuGestionActionPerformed);
        menuAdministracion.add(itemMenuGestion);

        jMenuBar1.add(menuAdministracion);

        menuConsultas.setText("Consultas");

        itemMenuCategoria.setText("Consultar por Categoria");
        itemMenuCategoria.addActionListener(this::itemMenuCategoriaActionPerformed);
        menuConsultas.add(itemMenuCategoria);

        itemMenuPrecio.setText("Consultar por Precio");
        itemMenuPrecio.addActionListener(this::itemMenuPrecioActionPerformed);
        menuConsultas.add(itemMenuPrecio);

        itemMenuNombre.setText("Consultar Por Nombre");
        itemMenuNombre.addActionListener(this::itemMenuNombreActionPerformed);
        menuConsultas.add(itemMenuNombre);

        jMenuBar1.add(menuConsultas);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dskPrincipal)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dskPrincipal)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void itemMenuGestionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemMenuGestionActionPerformed
       VistaGestion gestion = new VistaGestion();
       dskPrincipal.add(gestion);
       gestion.setVisible(true);
    }//GEN-LAST:event_itemMenuGestionActionPerformed

    private void itemMenuCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemMenuCategoriaActionPerformed
        VistaConsultaPorRubro ventanaCategoria = new VistaConsultaPorRubro();
        dskPrincipal.add(ventanaCategoria);
        ventanaCategoria.setVisible(rootPaneCheckingEnabled);
    }//GEN-LAST:event_itemMenuCategoriaActionPerformed

    private void itemMenuPrecioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemMenuPrecioActionPerformed
        VistaConsultaPorPrecio ventanaPrecio = new VistaConsultaPorPrecio();
        dskPrincipal.add(ventanaPrecio);
        ventanaPrecio.setVisible(true);
    }//GEN-LAST:event_itemMenuPrecioActionPerformed

    private void itemMenuNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemMenuNombreActionPerformed
       VistaConsultaPorNombre ventanaNombre = new VistaConsultaPorNombre();
       dskPrincipal.add(ventanaNombre);
       ventanaNombre.setVisible(true);
    }//GEN-LAST:event_itemMenuNombreActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new VistaPrincipal().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane dskPrincipal;
    private javax.swing.JMenuItem itemMenuCategoria;
    private javax.swing.JMenuItem itemMenuGestion;
    private javax.swing.JMenuItem itemMenuNombre;
    private javax.swing.JMenuItem itemMenuPrecio;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu menuAdministracion;
    private javax.swing.JMenu menuConsultas;
    // End of variables declaration//GEN-END:variables
}
